/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInteger extends SimpleNode {

  public int numvalue;

  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(eg2 p, int id) {
    super(p, id);
  }
  public void setVal(int n) {
    numvalue = n;
  }

  public int getInt() {
    return numvalue;
  }

  public String toString() {
    return Integer.toString(numvalue);
  }

  public SimpleNode reduce() {
    SimpleNode reducedExpr = this;
    if (children != null) {
      SimpleNode leftSubExpr = (SimpleNode)jjtGetChild(0);
      SimpleNode rightSubExpr = (SimpleNode)jjtGetChild(1);

      SimpleNode reducedLeftSubExpr = leftSubExpr.reduce(); // Recursively reduce the left sub expression
      SimpleNode reducedRightSubExpr = rightSubExpr.reduce(); // Recursively reduce the right sub expression
      jjtAddChild(reducedLeftSubExpr, 0);
      jjtAddChild(reducedRightSubExpr, 1);
      return reducedExpr;
   } else return reducedExpr;
  }

}
/* JavaCC - OriginalChecksum=0fecf608b19b57a85a1242508af7318d (do not edit this line) */
