/* Generated By:JJTree: Do not edit this line. ASTMyID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMyID extends SimpleNode {
  private String name;

  ASTMyID(int id){
    super(id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return name;
  }

  public SimpleNode reduce() {
    SimpleNode reducedExpr = this;
    if (children != null) {
      SimpleNode leftSubExpr = (SimpleNode)jjtGetChild(0);
      SimpleNode rightSubExpr = (SimpleNode)jjtGetChild(1);
	
      SimpleNode reducedLeftSubExpr = leftSubExpr.reduce(); // Recursively reduce the left sub expression
      SimpleNode reducedRightSubExpr = rightSubExpr.reduce(); // Recursively reduce the right sub expression
      jjtAddChild(reducedLeftSubExpr, 0);
      jjtAddChild(reducedRightSubExpr, 1);
      return reducedExpr;
   } else return reducedExpr;
  }

}
/* JavaCC - OriginalChecksum=ccf1e6e1b8578c98f15c4896cb3f8a64 (do not edit this line) */
