/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUBTRACT = 3;
  public int JJTMULT = 4;
  public int JJTDIVIDE = 5;
  public int JJTMODULO = 6;
  public int JJTMYID = 7;
  public int JJTINTEGER = 8;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Subtract",
    "Mult",
    "Divide",
    "Modulo",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=8df81dcaf1824d1b0ef9b768d12222df (do not edit this line) */
